version: "2.7"
server:
    exec_timeout: 10s
    command: "php public/index.php"
    env:
        APP_RUNTIME: Runtime\RoadRunnerSymfonyNyholm\Runtime
http:
    address: 0.0.0.0:8080
    access_logs: true
    pool:
        num_workers: 1

reload:
    interval: 1s
    patterns: [ ".php" ]
    services:
        http:
            recursive: true
            ignore: [ "vendor" ]
            patterns: [ ".php", ".go", ".md" ]
            dirs: [ "." ]
