name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Base
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/amd64
          target: base
          load: true
      - name: Test
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/amd64
          target: ci
          load: true
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          target: prod
          push: false
          #tags: org/repo:${{ github.sha }}
